unsetopt beep
bindkey -v

autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
zstyle ':completion:*:*:cdr:*:*' menu selection

# Get the real path to this file (since we've symlinked it to ~/.bashrc)
ZSHRC_DIR=$(dirname $(readlink -f ~/.zshrc))

for zrc_file in "$ZSHRC_DIR"/*.zrc; do
    . $zrc_file
done

if [ -f ~/.config/zshrc ]; then
	. ~/.config/zshrc
fi
