unsetopt beep
bindkey -v

autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
zstyle ':completion:*:*:cdr:*:*' menu selection

bindkey "^R" history-incremental-search-backward

# Get the real path to this file (since we've symlinked it to ~/.bashrc)
ZSHRC_DIR=$(dirname $(readlink -f ~/.zshrc))

# First load rc files
for zrc_file in "$ZSHRC_DIR"/**/*.zrc; do
    . $zrc_file
done

# Then general zsh files
# for zsh_file in "$ZSHRC_DIR"/**/*.zsh; do
#     . $zsh_file
# done

# Any final local customization
if [ -f ~/.config/zshrc ]; then
	. ~/.config/zshrc
fi
